name: 'action-file-to-env'
author: 'hocgin'
description: 'file content to env variable'
inputs:
  debug:
    required: false
    description: 'debug mode'
  type:
    required: false
    description: 'eg: github, local'
    default: 'github'
  file:
    required: false
    description: 'file path, eg: .github/workflows/file.txt'
  outkey:
    required: false
    description: 'output value key'
    default: 'value'
  #
  owner:
    required: false
    description: 'resp owner'
  repo:
    required: false
    description: 'resp'
  branch:
    required: false
    description: 'branch'
    default: 'main'
#outputs:
runs:
  using: node16
  main: dist/index.js
